import { useState, useCallback } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import logoFull from '../assets/logo-full.png'
import PracticeWorkspace from '../components/PracticeWorkspace'
import { generateRandomPuzzle, DIFFICULTIES } from '../lib/randomPuzzle'

/**
 * Practice mode: endless randomized problems generated by expanding a small
 * seed expression with inverse-law steps, so every problem is guaranteed
 * solvable and verified by the BFS solver.
 */
export default function PracticePage() {
  const navigate = useNavigate()
  const [difficulty, setDifficulty] = useState('medium')
  const [puzzle, setPuzzle] = useState(() => generateRandomPuzzle('medium'))
  const [solvedCount, setSolvedCount] = useState(0)
  const [loading, setLoading] = useState(false)
  const [lastSolvedKey, setLastSolvedKey] = useState(null)

  const regenerate = useCallback((diff) => {
    setLoading(true)
    // Defer to the next tick so the loading state can paint before the solver runs
    setTimeout(() => {
      const p = generateRandomPuzzle(diff)
      setPuzzle(p)
      setLastSolvedKey(null)
      setLoading(false)
    }, 50)
  }, [])

  const newPuzzle = useCallback(() => regenerate(difficulty), [regenerate, difficulty])

  const handleDifficultyChange = (key) => {
    if (key === difficulty) return
    setDifficulty(key)
    regenerate(key)
  }

  const handleStateChange = (snapshot) => {
    const key = `${puzzle?.expr}`
    if (snapshot.isComplete && lastSolvedKey !== key) {
      setLastSolvedKey(key)
      setSolvedCount(c => c + 1)
    }
  }

  return (
    <div className="h-screen flex flex-col bg-bg relative overflow-hidden">
      {/* Header */}
      <header className="relative w-full h-[60px] px-6 md:px-10 flex items-center justify-between bg-bg-card/85 backdrop-blur-md border-b border-border z-20 shrink-0">
        <div className="flex items-center gap-4 min-w-0">
          <Link to="/" className="shrink-0 hover:opacity-80 transition-opacity">
            <img src={logoFull} alt="Praxis" className="h-7 object-contain" />
          </Link>
          <div className="hidden sm:flex items-center gap-2">
            <span className="text-[11px] font-bold tracking-[1px] uppercase text-text-3">Practice</span>
            <span className="px-2 py-0.5 rounded-full bg-teal/10 border border-teal/30 text-teal text-[11px] font-bold">
              {solvedCount} solved
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Difficulty chips */}
          <div className="flex items-center gap-1 bg-bg border border-border rounded-lg p-1">
            {Object.entries(DIFFICULTIES).map(([key, d]) => (
              <button
                key={key}
                className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                  difficulty === key
                    ? 'bg-accent text-white shadow-sm'
                    : 'text-text-2 hover:bg-border hover:text-text-1'
                }`}
                onClick={() => handleDifficultyChange(key)}
              >
                {d.label}
              </button>
            ))}
          </div>
          <Link to="/sandbox" className="hidden sm:flex h-9 px-3 rounded-lg items-center justify-center text-[13px] font-bold text-text-2 bg-bg hover:bg-border hover:text-text-1 transition-all">
            🧪 Sandbox
          </Link>
          <Link to="/tutorial" className="hidden sm:flex h-9 px-3 rounded-lg items-center justify-center text-[13px] font-bold text-text-2 bg-bg hover:bg-border hover:text-text-1 transition-all">
            ▶ Tutorial
          </Link>
        </div>
      </header>

      {/* Workspace */}
      <main className="flex-1 min-h-0 p-3 sm:p-4">
        {loading || !puzzle ? (
          <div className="h-full flex items-center justify-center bg-white border border-border rounded-xl">
            <div className="flex flex-col items-center gap-3">
              <svg className="animate-spin h-7 w-7 text-accent" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              <span className="text-sm font-semibold text-text-3">Generating problem…</span>
            </div>
          </div>
        ) : (
          <PracticeWorkspace
            key={puzzle.expr}
            puzzle={puzzle}
            onStateChange={handleStateChange}
            onExit={() => navigate('/levels')}
            exitLabel="Levels"
            title={`Random Practice — ${DIFFICULTIES[difficulty].label}`}
            subtitle={`Simplify: ${puzzle.expr}`}
            onNewPuzzle={newPuzzle}
          />
        )}
      </main>
    </div>
  )
}
